### ISSUE TITLE
Support for database setup

### ISSUE THREAD

**Issue by dennisvang** [FAIRDataTeam/github-workflows#7]
The FDP test workflow requires either a MongoDB or a PostgreSQL database, depending on which version is running.

See e.g. [FDP develop]:

```yaml
      - name: Setup PostgreSQL DB
        if: matrix.os != 'macos-12'  # macOS is too slow for tests in GitHub Actions
        uses: ikalnytskyi/action-setup-postgres@v7
        id: postgres
        with:
          username: fdp
          password: fdp
          database: fdp_test
          port: 54321
```

This needs to be implemented in a reusable workflow as well.

[FDP develop]: https://github.com/FAIRDataTeam/FAIRDataPoint/blob/6b04fb8654509af1cd025f9fcb91f02f43a79086/.github/workflows/build.yml#L29
